# Generated by Django 4.0.1 on 2022-02-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
