# Generated by Django 4.0.2 on 2022-02-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eda_id',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
