# Generated by Django 4.0.2 on 2022-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_eda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='eda_id',
            field=models.IntegerField(default=0),
        ),
    ]
